"""
Report Generation Service for NexusAI
Generates structured Markdown & analytical executive summaries from live MongoDB data.
"""
# pyrefly: ignore [missing-import]
from bson import ObjectId
from datetime import datetime
from typing import Dict, Any, Optional
from app.services.decision_service import gather_decision_intelligence


async def generate_project_report(
    project_id: str,
    db,
    user_id: str,
    user_name: Optional[str] = "Project Manager",
    report_type: str = "executive_summary",
) -> Dict[str, Any]:
    """
    Generates a full Markdown report based on current project intelligence and persists it.
    """
    # 1. Gather all live intelligence data
    intel = await gather_decision_intelligence(project_id, db)

    project = intel["project"]
    observe = intel["observe"]
    predict = intel["predict"]
    explain = intel["explain"]
    recommend = intel["recommend"]
    optimize = intel["optimize"]

    p_name = project.get("name", "Project")
    generated_at_str = datetime.utcnow().strftime("%B %d, %Y at %H:%M UTC")

    # 2. Build Markdown content
    tasks_info = observe["tasks"]
    issues_info = observe["issues"]
    team_info = observe["team"]
    sprints_info = observe["sprints"]

    report_title = f"{p_name} — Decision Intelligence & Project Health Report"

    content = f"""# {report_title}

**Generated By:** {user_name}  
**Date:** {generated_at_str}  
**Report Type:** {report_type.replace('_', ' ').title()}  
**System:** NexusAI Enterprise Decision Intelligence Platform

---

## 1. Executive Summary

- **Project Status:** {project.get('status', 'N/A').upper()}
- **Priority Level:** {project.get('priority', 'N/A').upper()}
- **Overall Health Score:** **{predict.get('health_score', 'N/A')}/100** ({predict.get('health_status', 'Healthy')})
- **ML Risk Classification:** **{predict.get('risk_class', 'LOW')}** (Failure Probability: {predict.get('risk_probability', 0):.0%})
- **Schedule Forecast:** {predict.get('delay_days', 0)} day(s) projected delay (Probability: {predict.get('delay_probability', 0):.0%})
- **Budget Overrun Risk:** **{predict.get('budget_overrun_risk', 'LOW')}** (Projected Overrun: ${predict.get('budget_overrun_amount', 0):,.2f})

> **Key Assessment:** {explain.get('primary_driver', 'Project execution is within standard parameters.')}

---

## 2. Project Progress & Financial Utilization

| Metric | Target / Allocated | Current Value | Variance / Utilization |
| :--- | :--- | :--- | :--- |
| **Progress** | 100.0% | {project.get('progress', 0):.1f}% | {100 - project.get('progress', 0):.1f}% Remaining |
| **Total Budget** | ${project.get('budget', 0):,.2f} | ${project.get('current_expenditure', 0):,.2f} | {project.get('budget_utilization', 0):.1f}% Utilized |
| **Projected Final Cost** | ${project.get('budget', 0):,.2f} | ${predict.get('predicted_final_cost', project.get('budget', 0)):,.2f} | ${predict.get('budget_overrun_amount', 0):,.2f} |
| **Timeline Window** | {project.get('start_date', 'N/A')} | {project.get('end_date', 'N/A')} | Forecast: +{predict.get('delay_days', 0)} days |

---

## 3. Workload & Task Execution Status

- **Total Tasks Tracked:** {tasks_info.get('total', 0)}
- **Active Tasks:** {tasks_info.get('active', 0)}
- **Completed Tasks:** {tasks_info.get('completed', 0)} ({tasks_info.get('completion_rate', 0):.1f}%)
- **Overdue Tasks:** {tasks_info.get('overdue', 0)}
- **Blocked Tasks:** {tasks_info.get('blocked', 0)}
- **High / Critical Priority Tasks:** {tasks_info.get('high_priority', 0)}

---

## 4. Quality & Defect Analysis

- **Total Logged Issues:** {issues_info.get('total', 0)}
- **Open Unresolved Issues:** {issues_info.get('open', 0)}
- **Critical Severity Defects:** {issues_info.get('critical', 0)}
- **High Severity Defects:** {issues_info.get('high', 0)}
- **Resolved Issues:** {issues_info.get('resolved', 0)}

---

## 5. Team Capacity & Resource Workload

**Average Team Workload:** {team_info.get('overall_workload_ratio', 0):.1f}% of safe weekly capacity.  
**Overloaded Members (>100% capacity):** {team_info.get('overloaded_count', 0)}

| Team Member | Role | Specialization | Assigned Hours | Weekly Capacity | Workload Load % | Burnout Risk |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
"""

    for m in team_info.get("members", []):
        content += f"| {m['name']} | {m['role']} | {m.get('specialization', 'N/A')} | {m['assigned_hours']:.1f}h | {m['capacity_hours']:.1f}h | {m['workload_ratio']:.0f}% | {m.get('burnout_risk', 'LOW')} |\n"

    if not team_info.get("members"):
        content += "| No assigned team members recorded | - | - | - | - | - | - |\n"

    content += f"""
---

## 6. AI Decision Support & Actionable Recommendations

**Total Recommendations Generated:** {recommend.get('total_count', 0)}  
**Pending Manager Review:** {recommend.get('pending_count', 0)}

"""

    recs_list = recommend.get("recommendations", [])
    if recs_list:
        for idx, r in enumerate(recs_list, 1):
            content += f"""### Recommendation #{idx}: {r.get('title')}
- **Category:** {r.get('category')} | **Priority:** {r.get('priority').upper()} | **Status:** {r.get('status').upper()}
- **Why (Data Reason):** {r.get('reason')}
- **Suggested Manager Action:** {r.get('suggested_action')}
- **Expected Outcome:** {r.get('expected_impact')}

"""
    else:
        content += "*(No active recommendations pending for this project.)*\n\n"

    content += """---

## 7. Resource Optimization Plan

"""

    suggestions = optimize.get("reallocation_suggestions", [])
    if suggestions:
        content += f"**Identified Reallocation Moves ({len(suggestions)}):**\n\n"
        for idx, s in enumerate(suggestions, 1):
            from_name = s.get("from_employee_name") or s.get("from_employee", {}).get("name", "Overloaded Employee")
            to_name = s.get("employee_name") or s.get("to_employee", {}).get("name", "Available Employee")
            task_t = s.get("task_title", "Task")
            hours = s.get("task_hours", 0)

            content += f"{idx}. **Move Task:** `{task_t}` ({hours:.1f}h)  \n"
            content += f"   - **From:** {from_name}  \n"
            content += f"   - **To:** {to_name}  \n"
            content += f"   - **Reason:** {s.get('reason')}  \n"
            content += f"   - **Impact:** {s.get('expected_impact')}  \n\n"
    else:
        content += "*(No resource reallocations required at this time. Workload is balanced.)*\n\n"

    content += """---

## 8. Governance & Decision Confirmation

*Note: This report is synthesized by NexusAI Decision Intelligence for decision support. Final decisions, scope revisions, and assignments remain the sole responsibility of the Project Manager and authorized leadership.*

**Sign-off:** `_________________________`  
**Date:** `_________________________`
"""

    # 3. Persist into MongoDB `reports`
    report_doc = {
        "projectId": project_id,
        "generatedBy": user_id,
        "reportType": report_type,
        "title": report_title,
        "content": content,
        "createdAt": datetime.utcnow(),
        # Compatibility fields
        "project_id": project_id,
        "project_name": p_name,
        "generated_by": user_id,
        "generated_by_name": user_name,
        "report_type": report_type,
        "created_at": datetime.utcnow(),
    }

    result = await db.reports.insert_one(report_doc)
    report_doc["id"] = str(result.inserted_id)
    report_doc["_id"] = str(result.inserted_id)

    return report_doc
